### ISSUE TITLE
Felder für Kunden-Fenster

### ISSUE THREAD

**Issue by jannickfahlbusch** [sBeste/SGM-Final#3]
@huterdamm 

Kannst du im Kunden-anlegen-Fenster die Eigenschaften aus der Kundenklasse hinzufügen?

**Comment by ghost** [comment]
wie die eigenschaften ? 
du meinst den einzelnen feldern oder wie ?

**Comment by jannickfahlbusch** [comment]
Vorname, Nachname und Guthaben

Am 12. Dezember 2015 20:26:34 MEZ, schrieb huterdamm notifications@github.com:

**Comment by ghost** [comment]
Klar brauchen wir sonst noch was? 
Heute hab ich wenig zeit .... ich mach morgen alles. heißt morgen müssen wir alle iwie uns bissle bemühen iwas zu machen
